config/routes.rb
Rails.application.routes.draw do
  resources :signup, only: [:new, :create]
  resources :enrollments
  resources :sessions
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/enrollment.rb
class Enrollment < ApplicationRecord
  belongs_to :user

  def self.enrollments_of_week(ref = Date.today)
    ref = Date.today
    where(day: ref.beginning_of_week..ref.last_weekday)
  end
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password

  validates :email, :password, :name, presence: true
  validates :email, uniqueness: true
end

app/models/user/signin.rb
class User::Signin 
  def call(email, password)
    user = User.find_by(email: email)
    user && user.authenticate(password)
  end
end

app/models/user/signup.rb
class User::Signup
  def call(params)
    User.create!(params)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  def current_user
    warden.user
  end
  helper_method :current_user

  def warden
    env['warden']
  end

  def authenticate_user!
    unless current_user
      redirect_to new_session_url
    end
  end

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_action :authenticate_user!

  respond_to :json

  def index
    enrollments = Enrollment.enrollments_of_week
    @enrollments_presenter = EnrollmentsPresenter.new(enrollments, current_user)
  end

  def create
    respond_with Enrollment.new id: 10 #delete to Enrollment::Creation
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    warden.authenticate!
    redirect_to enrollments_url, notice: "Logged in!"
  end

  def destroy
    warden.logout
    redirect_to root_url, notice: "Logged out!"
  end
end

app/controllers/signup_controller.rb
class SignupController < ApplicationController
  respond_to :html

  def new
    @new_user = SignupOperation.new(User.new)
  end

  def create
    @new_user = SignupOperation.new(User.new).call(user_params)
    respond_with @new_user, location: -> { enrollments_path }
  end

  private

  def user_params
    params.require(:user).permit(:email, :name, :password, :password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def this_week_days
    ref = Date.today
    ref.beginning_of_week..ref.last_weekday
  end
end

app/views/enrollments/index.html.erb
<h2>Reserva de Sala</h2>
<table class='table'>
  <thead>
  <tr>
  <th>Horário</th>
  <% this_week_days.each do |day| %>
    <th><%= day.strftime("%A") %> </th>
    <% end %>
  </tr>
  </thead>

  <tbody>
    <% (6..23).each do |t| %>
    <tr>
      <td><%= t %></td>
      <% this_week_days.each do |day| %>
         <td> <%= @enrollments_presenter.render_link_for(day,t) %>  </td>
      <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Roomanagement</title>
    <%= csrf_meta_tags %>
<link href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class='container'>
      <%= yield %>
    </div>
  </body>


    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</html>

app/views/rooms/index.html.erb
oe

app/views/signup/new.html.erb
<%= simple_form_for(@new_user, url: signup_index_path, html: {class: 'form-horizontal'}) do |f| %>
    <%= f.input :name %>
    <%= f.input :email %>
    <%= f.input :password %>
    <%= f.input :password_confirmation %>
    <%= f.submit %>
<% end %>